language: rust

matrix:
  include:
    - os: linux
      rust: 1.10.0
      script: cargo test
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - cargo build
  - cargo build --no-default-features
  - cargo test

  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
